{
 "title": "dp-probe",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Events (totals)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_events_posted_total", "legendFormat": "Posted" },
    { "expr": "probe_events_received_total", "legendFormat": "Received" },
    { "expr": "probe_events_lost_total", "legendFormat": "Lost" }
   ]
  },
  {
   "title": "Posted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(probe_events_posted_total[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "round(increase(probe_events_posted_total[3m]))",
     "legendFormat": "3m"
    },
    {
     "expr": "round(increase(probe_events_posted_total[10m]))",
     "legendFormat": "10m"
    }
   ]
  },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(probe_events_received_total[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "round(increase(probe_events_received_total[3m]))",
     "legendFormat": "3m"
    },
    {
     "expr": "round(increase(probe_events_received_total[10m]))",
     "legendFormat": "10m"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(probe_events_lost_total[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "round(increase(probe_events_lost_total[3m]))",
     "legendFormat": "3m"
    },
    {
     "expr": "round(increase(probe_events_lost_total[10m]))",
     "legendFormat": "10m"
    }
   ]
  },
  {
   "title": "Events sent / min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(probe_events_posted_total[1m]) * 60",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(probe_events_posted_total[3m]) * 60",
     "legendFormat": "3m"
    },
    {
     "expr": "rate(probe_events_posted_total[10m]) * 60",
     "legendFormat": "10m"
    }
   ]
  },
  {
   "title": "Events received / min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(probe_events_received_total[1m]) * 60",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(probe_events_received_total[3m]) * 60",
     "legendFormat": "3m"
    },
    {
     "expr": "rate(probe_events_received_total[10m]) * 60",
     "legendFormat": "10m"
    }
   ]
  },
  {
   "title": "Events missing (share)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "probe_events_missing_1m_share", "legendFormat": "1m" },
    { "expr": "probe_events_missing_3m_share", "legendFormat": "3m" },
    { "expr": "probe_events_missing_10m_share", "legendFormat": "10m" }
   ]
  },
  {
   "title": "Events lost / min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(probe_events_lost_total[1m]) * 60",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(probe_events_lost_total[3m]) * 60",
     "legendFormat": "3m"
    },
    {
     "expr": "rate(probe_events_lost_total[10m]) * 600",
     "legendFormat": "10m"
    },
    {
     "expr": "rate(probe_events_lost_total[1h]) * 600",
     "legendFormat": "1h"
    }
   ]
  },
  {
   "title": "Event latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_event_latency", "legendFormat": "Latency" },
    {
     "expr": "avg_over_time(probe_event_latency[10m])",
     "legendFormat": "Average latency"
    },
    {
     "expr": "max_over_time(probe_event_latency[10m])",
     "legendFormat": "Max latency"
    },
    {
     "expr": "quantile_over_time(0.90, probe_event_latency[10m])",
     "legendFormat": "90% latency"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 29 },
   "targets": [
    { "expr": "probe_event_latency" }
   ]
  }
 ]
}