global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "probe_local"
    metrics_path: '/' # Defaults to /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"] # Resolve to the internal IP address used by the host
