name: Deploy to production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: eu-west-1

      - name: Deploy to aws fargate prod
        run: |
          aws ecs update-service --force-new-deployment --service probe --cluster dataplatform-probe --region eu-west