name: Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_dev:
    uses: ./.github/workflows/deploy_dev.yml
    secrets:
      AWS_ACCESS_KEY_DEV: ${{ secrets.AWS_ACCESS_KEY_DEV }}
      AWS_SECRET_ACCESS_KEY_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

  deploy_prod:
    uses: ./.github/workflows/deploy_prod.yml
    needs: deploy_dev
    secrets:
      AWS_ACCESS_KEY_PROD: ${{ secrets.AWS_ACCESS_KEY_PROD }}
      AWS_SECRET_ACCESS_KEY_PROD: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
